//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwimmerManagmentUI.Queries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QueriesManager {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QueriesManager() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwimmerManagmentUI.Queries.QueriesManager", typeof(QueriesManager).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Please review.
        ///
        ///SELECT CoachID, 
        ///       CoachName, 
        ///       C_Address AS [Address], 
        ///       Achievement, 
        ///       Salary, 
        ///       StartDateOfWork, 
        ///       TrainingDiploma
        ///FROM tblCoach;.
        /// </summary>
        internal static string GetAllCoaches {
            get {
                return ResourceManager.GetString("GetAllCoaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Please review
        ///
        ///SELECT TeamID, 
        ///       TeamName, 
        ///       MinimumAge, 
        ///       MaximumAge, 
        ///       Competitive
        ///FROM tblTeam
        ///WHERE(Coach = @coachId);.
        /// </summary>
        internal static string GetTeamsForCoach {
            get {
                return ResourceManager.GetString("GetTeamsForCoach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Please review.
        ///
        ///SELECT s.SwimmerID, 
        ///       MIN(s.FirstName) AS FirstName, 
        ///       MIN(s.LastName) AS LastName, 
        ///       MIN(DATEDIFF(YEAR, s.BirthDate, GETDATE())) AS Age, 
        ///       COUNT(*) AS NumberOfTrainings
        ///FROM tblPotentialSwimmer AS ps
        ///     INNER JOIN tblSwimmer AS s ON ps.PotentialSwimmerID = s.SwimmerID
        ///     INNER JOIN tblSwimmerTraining AS st ON ps.PotentialSwimmerID = st.SwimmerID
        ///WHERE(ps.DateOfFirstContact &gt;= DATEADD(MONTH, @monthsToAdd, GETDATE()))
        ///GROUP BY s.SwimmerID
        ///UNION
        ///SELEC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PotentialsContactAndByGender {
            get {
                return ResourceManager.GetString("PotentialsContactAndByGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Please review.
        ///
        ///SELECT rs.SwimmerID, 
        ///       s.FirstName, 
        ///       s.LastName, 
        ///       s.Gender, 
        ///       rs.Team, 
        ///       rs.TutorID
        ///FROM tblRegularSwimmer AS rs
        ///     LEFT OUTER JOIN tblSwimmerTraining AS st ON rs.SwimmerID = st.SwimmerID
        ///     INNER JOIN tblSwimmer AS s ON rs.SwimmerID = s.SwimmerID
        ///WHERE(st.SwimmerID IS NULL);.
        /// </summary>
        internal static string SwimmersWithoutTraining {
            get {
                return ResourceManager.GetString("SwimmersWithoutTraining", resourceCulture);
            }
        }
    }
}
